server:
  port: 9000

spring:
  application:
    name: eurekaserver

  config:
    import: optional:configserver:http://localhost:8071/
    
management:
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    env:
      enabled: true  
  endpoint:
    shutdown:
      enabled: true
    health:
      probes:
        enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    
info:
  app: 
    name: Eureka server Microservice
    description: Vicheak Bank Account App
    version: 1.0.0
    
logging:
  level:
    '[com.vicheak.bank.eurekaserver]': DEBUG
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"